name: Release Obsidian Plugin

on:
    push:
        tags:
            - "*.*.*" # Match semantic version tags (no 'v' prefix)

permissions:
    contents: write
    pull-requests: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Full git history for version verification

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Verify manifest version matches tag
              run: |
                  TAG_VERSION="${GITHUB_REF#refs/tags/}"
                  MANIFEST_VERSION=$(cat manifest.json | jq -r '.version')

                  if [ "$TAG_VERSION" != "$MANIFEST_VERSION" ]; then
                    echo "Error: Tag version ($TAG_VERSION) does not match manifest version ($MANIFEST_VERSION)"
                    exit 1
                  fi
                  echo "Version verified: $TAG_VERSION"

            - name: Build plugin
              run: npm run build

            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: ${{ github.ref_name }}
                  draft: false
                  prerelease: false
                  body: |
                      ## Life Navigator ${{ github.ref_name }}

                      Please refer to the [changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.

                      ### Installation
                      - From Obsidian: Open Settings > Community Plugins > Browse and search for "Life Navigator"
                      - Manual: Download the files from this release and place them in your vault's `.obsidian/plugins/life-navigator` folder

            - name: Upload main.js
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./main.js
                  asset_name: main.js
                  asset_content_type: application/javascript

            - name: Upload manifest.json
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./manifest.json
                  asset_name: manifest.json
                  asset_content_type: application/json

            - name: Check if styles.css exists
              id: check_styles
              run: |
                  if [ -f "styles.css" ]; then
                    echo "exists=true" >> $GITHUB_OUTPUT
                  else
                    echo "exists=false" >> $GITHUB_OUTPUT
                  fi

            - name: Upload styles.css if it exists
              uses: actions/upload-release-asset@v1
              if: steps.check_styles.outputs.exists == 'true'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./styles.css
                  asset_name: styles.css
                  asset_content_type: text/css
